language: cpp

compiler: clang

os:
    - linux
    - osx

notifications:
    email:
        recipients:
            - andersd@riseup.net
        on_success: never
        on_failure: always

before_install:
    - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; sudo apt-get install -qq dh-autoreconf libjsoncpp-dev libcurl4-gnutls-dev libncurses5-dev; fi
    - if [ $TRAVIS_OS_NAME = osx ]; then brew install jsoncpp; fi

before_script:
    - ./autogen.sh

script:
    - ./configure && make
